version: '3'
services:
  postgre:
    container_name: postgre
    image: postgres:alpine

    networks:
      - web
    volumes:
      - ./datadir/postgre:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_USER: $PG_USERNAME
    # network_mode: "host"
  mongo:
    image: mongo:3.6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    ports:
      - "27017:27017"
    networks:
      - web
    volumes:
      - ./datadir/mongo:/data/db
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    container_name: elastic
    restart: always
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - web
    volumes:
      - ./datadir/elastic:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.3
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    networks:
      - web
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - web
    volumes:
      - ./datadir/redis:/data
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./datadir/mosquitto:/etc/mosquitto
      - ./datadir/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
networks:
  web:
    name: web
